---
- hosts: linux
  gather_facts: yes
  become: yes

  tasks:
    - name: Install Update Manager Core
      apt:
        name: update-manager-core
        state: latest
        update_cache: true

    - name: Expose Backup SSH Port
      command: iptables -I INPUT -p tcp --dport 1022 -j ACCEPT

    - name: Upgrading Software
      command: do-release-upgrade -f DistUpgradeViewNonInteractive

    - name: Check if a reboot is required.
      stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required_file

    - name: Reboot the server (if required).
      reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies that are no longer required.
      apt:
        autoremove: yes

    - name: Close Backup SSH Port
      command: iptables -I INPUT -p tcp --dport 1022 -j DROP